name: th
description: "A Flutter Foodapp By sutee-f&thana5100"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  geolocator: ^12.0.0
  geocoding: ^2.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.5
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
